
export interface Grades {
  name: string;
  unit_1: {
    espanol: number,
    matematicas: number,
    historia: number,
    biologia: number,
    geografia: number,
    fce: number,
    tecnologia: number,
    vida: number,
    ingles: number,
    musica: number,
  },
  unit_2: {
    espanol: number,
    matematicas: number,
    historia: number,
    biologia: number,
    geografia: number,
    fce: number,
    tecnologia: number,
    vida: number,
    ingles: number,
    musica: number,
  },
  unit_3: {
    espanol: number,
    matematicas: number,
    historia: number,
    biologia: number,
    geografia: number,
    fce: number,
    tecnologia: number,
    vida: number,
    ingles: number,
    musica: number,
  },
}
export const gradesAttributesMapping = {
  name: 'Nombre del alumno',
  unit_1: {
    _prefix: 'Unidad 1',
    espanol: 'Español 1',
    matematicas: 'Matemáticas 1',
    historia: 'Historia 1',
    biologia: 'Biología 1',
    geografia: 'Geografía 1',
    fce: 'Formación Cívica y Ética 1',
    tecnologia: 'Tecnología 1',
    vida: 'Vida Saludable 1',
    ingles: 'Inglés 1',
    musica: 'Música 1',
  },
  unit_2: {
    _prefix: 'Unidad 2',
    espanol: 'Español 1',
    matematicas: 'Matemáticas 1',
    historia: 'Historia 1',
    biologia: 'Biología 1',
    geografia: 'Geografía 1',
    fce: 'Formación Cívica y Ética 1',
    tecnologia: 'Tecnología 1',
    vida: 'Vida Saludable 1',
    ingles: 'Inglés 1',
    musica: 'Música 1',
  },
  unit_3: {
    _prefix: 'Unidad 3',
    espanol: 'Español 1',
    matematicas: 'Matemáticas 1',
    historia: 'Historia 1',
    biologia: 'Biología 1',
    geografia: 'Geografía 1',
    fce: 'Formación Cívica y Ética 1',
    tecnologia: 'Tecnología 1',
    vida: 'Vida Saludable 1',
    ingles: 'Inglés 1',
    musica: 'Música 1',
  },
}
