export enum CourseLevel {
  Maternal, Preescolar, Primaria, Secundaria, Docente, Inespecífico
}
export enum State {
  STATE_UNSPECIFIED,
  PUBLISHED,
  DRAFT,
  DELETED
}
/** State of the course. If unspecified, the default state is `PROVISIONED`. */
export enum CourseState {
  COURSE_STATE_UNSPECIFIED,
  ACTIVE,
  ARCHIVED,
  PROVISIONED,
  DECLINED,
  SUSPENDED,
}
export enum AnnouncementState {
  ANNOUNCEMENT_STATE_UNSPECIFIED,
  PUBLISHED,
  DRAFT,
  DELETED
}
export enum SharedMode {
  UNKNOWN_SHARE_MODE,
  VIEW,
  EDIT,
  STUDENT_COPY
}
export enum CourseWorkType {
  COURSE_WORK_TYPE_UNSPECIFIED,
  ASSIGNMENT,
  SHORT_ANSWER_QUESTION,
  MULTIPLE_CHOICE_QUESTION
}
export enum AssigneeMode {
  ASSIGNEE_MODE_UNSPECIFIED,
  ALL_STUDENTS,
  INDIVIDUAL_STUDENTS
}
export enum SubmissionModificationMode {
  SUBMISSION_MODIFICATION_MODE_UNSPECIFIED,
  MODIFIABLE_UNTIL_TURNED_IN,
  MODIFIABLE
}
export enum SubmissionState {
  STATE_UNSPECIFIED, NEW, CREATED, TURNED_IN, RETURNED, RECLAIMED_BY_STUDENT, STUDENT_EDITED_AFTER_TURN_IN
}
export enum Permission {
  PERMISSION_UNSPECIFIED, CREATE_COURSE
}
export enum GradeChangeType {
  UNKNOWN_GRADE_CHANGE_TYPE, DRAFT_GRADE_POINTS_EARNED_CHANGE, ASSIGNED_GRADE_POINTS_EARNED_CHANGE, MAX_POINTS_CHANGE
}
